- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For desktop background, set bg image to '{{ background_image_path }}'"
    key: "/org/mate/desktop/background/picture-filename"
    value: "'{{ background_image_path }}'"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For desktop background, set bg image opacity to {{ mate_de_background_image_opacity }}"
    key: "/org/mate/desktop/background/picture-opacity"
    value: "{{ mate_de_background_image_opacity }}"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For desktop background, set bg image coverage to '{{ mate_de_background_image_coverage }}'"
    key: "/org/mate/desktop/background/picture-options"
    value: "'{{ mate_de_background_image_coverage }}'"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For desktop background, set bg primary color to '{{ mate_de_background_primary_color }}'"
    key: "/org/mate/desktop/background/primary-color"
    value: "'{{ mate_de_background_primary_color }}'"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For desktop background, set bg secondary color to '{{ mate_de_background_secondary_color }}'"
    key: "/org/mate/desktop/background/secondary-color"
    value: "'{{ mate_de_background_secondary_color }}'"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For desktop background, set bg colors transition to '{{ mate_de_background_colors_transition }}'"
    key: "/org/mate/desktop/background/color-shading-type"
    value: "'{{ mate_de_background_colors_transition }}'"

