- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For fonts, set window-title font to '{{ mate_de_font_for_window_titles }}'"
    key: "/org/mate/marco/general/titlebar-font"
    value: "'{{ mate_de_font_for_window_titles }}'"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For fonts, set desktop-background font to '{{ mate_de_font_for_desktop_background }}'"
    key: "/org/mate/caja/desktop/font"
    value: "'{{ mate_de_font_for_desktop_background }}'"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For fonts, set main application font to '{{ mate_de_font_for_apps }}'"
    key: "/org/mate/desktop/interface/font-name"
    value: "'{{ mate_de_font_for_apps }}'"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For fonts, set document/user-input font to '{{ mate_de_font_for_docs }}'"
    key: "/org/mate/desktop/interface/document-font-name"
    value: "'{{ mate_de_font_for_docs }}'"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For fonts, set monospace font to '{{ mate_de_font_for_monospace }}'"
    key: "/org/mate/desktop/interface/monospace-font-name"
    value: "'{{ mate_de_font_for_monospace }}'"

