- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For keyboard, set enable-keypress-repeat to '{{ repeat_on }}'"
    key: "/org/mate/desktop/peripherals/keyboard/repeat"
    value: "{{ repeat_on }}"
    repeat_on: "{{ 'false' if (mate_de_keyboard_repeat_rate_ms == 'none') else 'true' }}"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For keyboard, set keypress-repeat-rate to {{ mate_de_keyboard_repeat_rate_ms }} millisec"
    key: "/org/mate/desktop/peripherals/keyboard/rate"
    value: "{{ mate_de_keyboard_repeat_rate_ms }}"
  when: mate_de_keyboard_repeat_delay_ms != 'none'

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For keyboard, set keypress-repeat-delay to {{ mate_de_keyboard_repeat_delay_ms }} millisec"
    key: "/org/mate/desktop/peripherals/keyboard/delay"
    value: "{{ mate_de_keyboard_repeat_delay_ms }}"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For keyboard, set enable-audible-bell to '{{ bell_on }}'"
    key: "/org/mate/desktop/peripherals/keyboard/bell-mode"
    value: "'{{ bell_on }}'"
    bell_on: "{{ 'on' if mate_de_keyboard_bell_enable else 'off' }}"

